# Generated by Django 4.2.7 on 2025-08-10 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('trigger_on_lead_creation', models.BooleanField(default=False)),
                ('trigger_on_status_change', models.JSONField(blank=True, default=list)),
                ('trigger_on_priority_change', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('delay_start_days', models.IntegerField(default=0, help_text='Days to wait before starting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_sequences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('template_type', models.CharField(choices=[('welcome', 'Welcome Email'), ('follow_up', 'Follow-up Email'), ('quote_request', 'Quote Request'), ('proposal', 'Proposal Email'), ('thank_you', 'Thank You Email'), ('nurture', 'Nurture Campaign'), ('appointment', 'Appointment Confirmation'), ('custom', 'Custom Template')], max_length=20)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField(help_text='HTML content of the email')),
                ('body_text', models.TextField(blank=True, help_text='Plain text version')),
                ('variables_help', models.TextField(blank=True, help_text='Available variables: {{lead_name}}, {{company}}, {{user_name}}, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_shared', models.BooleanField(default=False, help_text='Share with team')),
                ('usage_count', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100)),
                ('provider', models.CharField(choices=[('smtp', 'Custom SMTP'), ('gmail', 'Gmail'), ('outlook', 'Outlook'), ('sendgrid', 'SendGrid'), ('ses', 'Amazon SES')], max_length=20)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('use_tls', models.BooleanField(default=True)),
                ('use_ssl', models.BooleanField(default=False)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=100)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('daily_limit', models.IntegerField(default=500, help_text='Daily email limit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('send_now', models.BooleanField(default=False)),
                ('target_all_leads', models.BooleanField(default=False)),
                ('target_statuses', models.JSONField(blank=True, default=list)),
                ('target_priorities', models.JSONField(blank=True, default=list)),
                ('target_sources', models.JSONField(blank=True, default=list)),
                ('batch_size', models.IntegerField(default=50, help_text='Emails per batch')),
                ('delay_between_batches', models.IntegerField(default=60, help_text='Seconds between batches')),
                ('total_recipients', models.IntegerField(default=0)),
                ('emails_sent', models.IntegerField(default=0)),
                ('emails_failed', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.emailconfiguration')),
                ('specific_leads', models.ManyToManyField(blank=True, to='leads.lead')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField(blank=True)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(max_length=100)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(blank=True, max_length=100)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('replied', 'Replied'), ('bounced', 'Bounced'), ('failed', 'Failed'), ('spam', 'Marked as Spam')], default='queued', max_length=20)),
                ('external_id', models.CharField(blank=True, help_text="Provider's message ID", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('clicked_at', models.DateTimeField(blank=True, null=True)),
                ('open_count', models.IntegerField(default=0)),
                ('click_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.emailcampaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='leads.lead')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='communications.emailtemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('bounced', 'Bounced'), ('spam', 'Marked as Spam'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('clicked_url', models.URLField(blank=True)),
                ('bounce_reason', models.TextField(blank=True)),
                ('provider_data', models.JSONField(blank=True, default=dict)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_events', to='communications.email')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email', 'event_type'], name='communicati_email_i_3e791c_idx'), models.Index(fields=['timestamp'], name='communicati_timesta_a00251_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmailSequenceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('delay_days', models.IntegerField(help_text='Days after previous step (or sequence start)')),
                ('send_only_if_not_replied', models.BooleanField(default=True)),
                ('send_only_if_status', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='communications.emailsequence')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.emailtemplate')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('sequence', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='EmailSequenceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('current_step', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('emails_sent', models.IntegerField(default=0)),
                ('last_email_sent', models.DateTimeField(blank=True, null=True)),
                ('has_replied', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.lead')),
                ('sequence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.emailsequence')),
            ],
            options={
                'ordering': ['-enrolled_at'],
                'unique_together': {('sequence', 'lead')},
            },
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['tracking_id'], name='communicati_trackin_27c913_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['status', 'created_at'], name='communicati_status_b6228c_idx'),
        ),
        migrations.AddIndex(
            model_name='email',
            index=models.Index(fields=['lead', 'created_at'], name='communicati_lead_id_4d1c46_idx'),
        ),
    ]
