# Generated by Django 4.2.7 on 2025-08-10 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_date_range', models.CharField(choices=[('today', 'Today'), ('week', 'This Week'), ('month', 'This Month'), ('quarter', 'This Quarter'), ('year', 'This Year')], default='month', max_length=20)),
                ('show_welcome_message', models.BooleanField(default=True)),
                ('auto_refresh_interval', models.IntegerField(default=300)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_lead', 'New Lead Assigned'), ('lead_status_change', 'Lead Status Change'), ('overdue_follow_up', 'Overdue Follow-up'), ('target_achieved', 'Target Achieved'), ('daily_summary', 'Daily Summary'), ('weekly_report', 'Weekly Report')], max_length=20)),
                ('email_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='KPITarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_type', models.CharField(choices=[('leads_created', 'Leads Created'), ('leads_converted', 'Leads Converted'), ('revenue_generated', 'Revenue Generated'), ('calls_made', 'Calls Made'), ('emails_sent', 'Emails Sent'), ('meetings_scheduled', 'Meetings Scheduled')], max_length=20)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'kpi_type', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('widget_type', models.CharField(choices=[('stats_card', 'Statistics Card'), ('chart', 'Chart Widget'), ('recent_leads', 'Recent Leads'), ('top_performers', 'Top Performers'), ('activity_feed', 'Activity Feed'), ('calendar', 'Calendar Widget')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('position', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('user', 'widget_type')},
            },
        ),
    ]
